maven:
  stage: build
  image: openjdk:13-alpine
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  cache:
    paths:
      - ./.m2/repository/
  before_script:
    - apk update -q && apk add -q protobuf && apk add -q maven
  script:
    - "mvn clean package --batch-mode"
  artifacts:
    paths:
      - "*/target/*.jar"

push-docker-core:
  stage: deploy
  only:
    - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/docker-core --dockerfile $CI_PROJECT_DIR/docker-core/Dockerfile --destination $CI_REGISTRY_IMAGE --cache=true
