language: java
install:
- wget https://github.com/protocolbuffers/protobuf/archive/v3.11.3.tar.gz
- tar -xzvf v3.11.3.tar.gz
- pushd protobuf-3.11.3 && ./autogen.sh && ./configure --prefix=/usr && make && sudo
  make install && popd
- protoc --version
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: UXbaJd0eyig3nyGos8vmsS9ok3zwIebKuKMzqk204FOrAzFoNtMvzUVocBIi3TCxBNQRyT1ssdQ5rJ1K1S/4tuJERcP+T3X3eYWwg+sW+6TjIUgWgJ0JhDFRTqfePjgOnd3FSpRjJuKVxS97M3PyzjtGbc5FGqTCFmgHf5aPfKpCEDs95yd92+y1isBfk2Q+UeYRZs/36ULP+qfXXSS10sCkshyAZe/SeVtcAQVrCClUbT/FV0wScpH2lYKp2yplmrfurQ0E42KFcYaZKD1RGRCjTMCN9+LHOzFz5AmXsrjW4Q1HBm7UgFzkbbsgN+36U2xPneW060iW+C1eSZci4p4NQPnenWaLTU+VvqhiLDcff4vWf8bgG27iFX3Q7OnogCayXaW1TKDsSWrw15PDHMA93yWyL41BP9LGjnmYFRqvg6sN/D1CfffC3xNOLVMjgjZiY5Z5yzzbqv2XiYxh2IV7Q/3POsjzIh1mxcnjJIqQ188J4IJL0xlNq6sXhUX4M8wqOj5q+f6Hn3bsuhSBI7fzQYQ3zQbNJ3MlNM6IxzGqVxgPt1K4B1mCmfe7gQGR3IWli0yQw1LiEvqm4x9vRW6xMYlRSJbVPtAYGFjM4tWrq6yWGOy7p6b5xqT58dTyg4S/iqd0HbCLHun2qEFkTlujut65SJ4+x/DFP7D/6fM=
  file: adapter/target/adapter-$project_version.jar
  skip_cleanup: true
  on:
    repo: nalim2/SFSC
  name: $project_version

