language: java
deploy:
  provider: releases
  api_key:
    secure: R9jdCd4NPn+3NZFtKLJcVZTSW6WZqWIyZkCyFf31nbVS0eFUEpaaSGAiKCuzJkkA+AAxb2g4dSN+QJawJg883zfUGcbCKI1EJLKPkEv36hGTOkAUt9GDHjY0++5t3JVg30WZUh3c5nYdeIGQZSDAEasFeEYuwpi0U7efnBcHJPcAuqYOonszJA4qwr9IPuSCe1vW42AVkPoYdSluto4oPvJ64HyrYnvJm9auVrBxC1QxbdmlGFKHlxQQKTDWLb+VgQ8CtcawthSR9k4K+oCEc1mktZcKoQES3+8I9df+VFbDnWVkMAvvrx4aWfAcQQ+SToiVhQdWhiynRdj0CQbJAJsxZRPAOShT4u+2wSuLLUV8HTUyNAYJid0j1DXM9bPBx8NCjFmvmuCob4p/hjzo+MYaibNZyX1hdb5IJ/8+PZQSoxtInkNGO33wuDO/4NbmH6Y7m7twF/QBNBLp7x86C8oiuROiKkz2WD/OjT3K+SXdx37ghPlBFq+OqdcQqKNrn++vLWwkPgmy5XTFVQN1XI3KZw84WqW0DdeMLx6JiJW1Zn8QC7plTlBswP2K3XAVwfggdRxyW5bEbfJe93pFW23h/tWM49uxV/0FxaZoQU/Za7lQ6CFZRSswIBujJexTALFWx1DJqaPiP0LJEWLP7FaiddvqwsTLc+6R290AAp4=
  file: 
      -"adapter/target/adapter-$project_version.jar"
  skip_cleanup: true
  on:
    repo: nalim2/SFSC
  name: $project_version

