language: java
install:
- wget https://github.com/protocolbuffers/protobuf/archive/v3.11.3.tar.gz
- tar -xzvf v3.11.3.tar.gz
- pushd protobuf-3.11.3 && ./autogen.sh && ./configure --prefix=/usr && make && sudo
  make install && popd
- protoc --version
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
- ls ./target/
- ls ./adapter/target/
deploy:
  provider: releases
  api_key:
    secure: RIXBkZUnUjiZ7UX5lAi30apKI0NPSzlzyMZQ4TuMrhFwzZ8NND0/MtdQVc+TZOWrD3idPE08krIpHm4AzMStNcccLZ6bPw4n83EENhc7zbOzpzyNspXlDMqTA+f2GstzdaW4T10LbEDMNs6rnbuKg5Dg6QHzbd83uS72qqHpdDPXLP1VITMo+BlSCbFUA2g87BgwYxqBoYbLsK7CziZd5BwXjGTZ8QfQW9X4j7L/kCzGb4ovCrsXwRSG7AEqM45z9A6EJUVYJat1nIJbZxbmDYqIYaSPh9oaQvuQ5ypB1+vq0rwH+zTP3x5QHU8MBmRFk0MiqnPgn+NF6/jO01+u1dhzzpQEtfdGdbddaJLDyjB8a+OlMW/t9zi96Gi/Lj1I1qjLOPbg6uxQDYV/OnYkDCxoa7ba0tvZ5xAJ1XdSQgJY3yyK1RhnhuodWwz2a72IP2d7WY1XAjfhznU5n/BsNVZWdVN//9o5aPumI06LPCqHP8TYcAh/m4n0kvojOJwg6E6WKZO6/4XxUaTTSo75u6PUMM/JUkhJE1J7jQgLx3fRfpljwBDZ30gnUqwcYR1bfsnTQz76p/zN7YtBdo7gMZf1zrrHAsyEC4cPdE6gtAugjxeST1rmnnRnJT0FkZ4p93ZQMhBKvNIttmHQNFXyLaxR/wKXwscjDKgx97RIYSk=
  file: 
    - ./adapter/target/adapter-$project_version.jar
    - ./adapter/target/adapter.jar
    - ./proto/target/proto-$project_version.jar
    - ./proto/target/proto.jar
    - ./common-java/target/common-java-$project_version.jar
    - ./common-java/target/common-java.jar
    - ./core/target/core-$project_version.jar
    - ./core/target/core.jar
    - ./docker-core/target/docker-core-$project_version.jar
    - ./docker-core/target/docker-core.jar
    - ./framework/target/framework-$project_version.jar
    - ./framework/target/framework.jar
    - ./hello-world/target/hello-world-$project_version.jar
    - ./hello-world/target/hello-world.jar
    - ./target/sfsc-$project_version.jar
    - ./taget/(sfsc.jar
  
  skip_cleanup: true
  on:
    repo: nalim2/SFSC
  name: $project_version

