language: java
install:
- wget https://github.com/protocolbuffers/protobuf/archive/v3.11.3.tar.gz
- tar -xzvf v3.11.3.tar.gz
- pushd protobuf-3.11.3 && ./autogen.sh && ./configure --prefix=/usr && make && sudo
  make install && popd
- protoc --version
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: N7q+EVyFpzbZ9xXaRwcyuC7+S59DPm7AlHHNljN5nQTpbarG84jP5hHdYZsP+NYG57xipVouT8Qm/YCipaga9mVE7+J+j9NI63Fd9smhXQH5A4B+tNUtcTQVcQ3af5GFXm1H0mSMdTvT7UyoBv1GFUiY1o0DaJF9STzDifbgogk0QGh7e+5YGPa094PCD1DnPADbrKVLxRdW6Bew81DflFE91LhU0Cnktu8aGS/HeI5IwdYfjPnQSYcpDDFBmgybG/LL/Am6IFakkGY1D42Z+QA62OWZSxQnhXNVLVJqECCl/kZOQDrc5cmQiR7MRBVcgIjVhkOpaeCgZx58E/cZ7VeL2CCx2acudLGdQArwuM1DiixJO5AojnRk0i6dWNUSqL3N6e6ydB9o9BYO4JcNcBQpyIJroHrIGIgr2EguxuOdLEPMZI9lP1xA0i08cH0UmM5WY3SfWB6PpYfHaG9Zirx6TRnhT7nrCCrJ08CHtisEPY+QrfoltFOH69zyjBcvDhLDjJvEwcWQkAVuaxxAmB5C7q4GZyR/0eeLDp+es9g2QtEiAuUt5I8RbbOWf1rluf07VE1gZNsShEz1sI/ut6VVdXBTbw9RttERD8iy5qw96fRkh8FebdB4HCC633+qNg/XhqQfsZUNog/+83K2MskYjUxW4yfwnzWtZAhmIyU=
  file: adapter/target/adapter-$project_version.jar
  skip_cleanup: true
  on:
    repo: nalim2/SFSC
  name: $project_version

