language: java
install:
- wget https://github.com/protocolbuffers/protobuf/archive/v3.11.3.tar.gz
- tar -xzvf v3.11.3.tar.gz
- pushd protobuf-3.11.3 && ./autogen.sh && ./configure --prefix=/usr && make && sudo
  make install && popd
- protoc --version
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: 0cdnyo5WdTktdrqH1+BjEHIgWcOvSsTgNZQ15vJs65rVj+eow+wjPtAcybel54nFW2jwA618o59EwMnAi00k79CjqaNDAUs7ids2y943GhVLdRgiR+jFWCTO9wemxAIg/NoH6XT/Xtcv7N4JboyHcgKMGsHj0IawgBFF//7+2kUwx2tWbahg9PCovYDyzs1gCcdRUxO+pHeYTkpT40eKBoRG5WUgVrtyISuQ/N6sHNcxqfnE1zyCrUoE09nhU5+n2ZgMyjobLkC+ujD2iUbSZvleB1wAerGZ0kDuv4xxYOvh1VkM45KZa5w6EbmRI8eBzrb4ayhHjY97ib9WuvxEUnxc5/QqDClmvbXj5ulVr5bh8Dg9EW/wBfWO/2cqfUgB0T1YMPRUIcdtUObVe8XeMituG1qy2P7LLcW21HKKEgVR1pP/Nb1ntCnM9X0A1dt3vL6u11ZQz5kSqo+gGq+DeNia+1h9ME1/BeOyzi3olymt80ek3b5L2Y1lyKqgqTp8cw4WmJYl5HnxxFKnm7N4lPTn7Us4gNBAWKuqEiZZ8CrKfJfzR+DHE5ypCEoijhRyQrSoH41xeALAoegKN0rMXfxBtrHq6vmKjeI2srx+lX4HQeFmwu8IPvAOVzkQYs8tgsBXwPay++MBey7n+kRNBSLVCzROMJZv/E+dWAWPeFY=
  file: adapter/target/adapter-$project_version.jar
  skip_cleanup: true
  on:
    repo: nalim2/SFSC
  name: $project_version

